# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    # https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition
    #
    # Cancel building pull requests when there aren't changes in the Doc directory.
    #
    # If there are no changes (git diff exits with 0) we force the command to return with 183.
    # This is a special exit code on Read the Docs that will cancel the build immediately.
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - cd docs
    - pip install -r requirements.txt
    - make singlehtml
    - mkdir _readthedocs
    - mv docs/build/singlehtml _readthedocs/html
# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Enable pdf download on readthedocs
formats:
  - htmlzip
  - epub
  - pdf

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt
