version: '1.0'
name: pipeline-20240330
displayName: pipeline-20240330
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
  schedule:
    - cron: '* 20 * * * ? *'
stages:
  - name: stage-ad2b7254
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: sc@opensca
        name: open_sca
        displayName: OpenSCA 开源组件检测
        detectPath: ./
        notify: []
        strategy:
          retry: '0'
strategy: {}
