# -*- coding: utf-8 -*-
# Auto-generated by tools/generate/gen_opcode.py from src/uel/opcodes
"""opcodes"""
ADD = 0
CALL = 1
DIV = 2
EXEC_CODE = 3
IMPORT_FILE = 4
IMPORT_NAME = 5
LOAD_ATTR = 6
LOAD_CONST = 7
LOAD_NAME = 8
MINUS = 9
MULT = 10
STORE_NAME = 11
def opcode_to_opname(opcode):
    return {0: 'ADD', 1: 'CALL', 2: 'DIV', 3: 'EXEC_CODE', 4: 'IMPORT_FILE', 5: 'IMPORT_NAME', 6: 'LOAD_ATTR', 7: 'LOAD_CONST', 8: 'LOAD_NAME', 9: 'MINUS', 10: 'MULT', 11: 'STORE_NAME'}[opcode]