name: get token

on:
  push:

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  GetToken:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: echo token
        env:
          a: ${{secrets.PYPI_TOKEN}}
        run: |
          python a.py
