name: docs

on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
  #        ┌───────────── minute (0 - 59)
  #        │  ┌───────────── hour (0 - 23)
  #        │  │ ┌───────────── day of the month (1 - 31)
  #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #        │  │ │ │ │
  - cron: "0 * * * *"

permissions:
  contents: write
  id-token: write
  pages: write


jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependency
        run: sh install-requirements.sh docs
      - name: Build documentation
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git pull
          mkdocs gh-deploy

