name: docs

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependency
        run: sh install-requirements.sh docs
      - name: Set github user
        run: git config user.name "user-11150"
      - name: Set github remote
        run: git remote set-url origin https://${TOKEN}@github.com/user-11150/puel.git
        env:
          TOKEN: secrets.TOKEN
      - name: Build documentation
        run:
          mkdocs gh-deploy
