name: docs

on:
  push:
    paths:
      - "docs/**"
      - "mkdocs.yml"

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependency
        run: pip install -r requirements/requirements-docs.txt
      - name: Build documentation
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git pull
          mkdocs gh-deploy

