name: docs

on:
  push:
    branches: [ master ]
  pull_request:

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependency
        run: sh install-requirements.sh docs
      - name: Build documentation
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          mkdocs gh-deploy

