name: docs

on:
  push:
    branches: [ master ]
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
  pull_request:
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependency
        run: sh install-requirements.sh docs
      - name: Build documentation
        run: mkdocs gh-develop
