name: Documentation

on:
  push:
    branches:
      - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - name: Set up Python
            uses: actions/setup-python@v4
            with:
                python-version: 3.11
          - name: Checkout directory, install dependences and commits
            run: |
                cd docs
                pip install -r ./requirements.txt
                make singlehtml
                git clone https://github.com/user-11150/puel.git --branch gh-pages --single-branch gh-pages
                cd gh-pages
                git remote set-url origin https://${GH_TOKEN}@github.com/user-11150/puel.git
                cp -r ../build/singlehtml/* ./
                touch .nojekyll
                git config --local user.email "3584434540@qq.com"
                git config --local user.name "user-11150"
                git add .
                git commit -m "Update documentation" -a || true
                # The above command will fail if no changes were present, so we ignore
                # that.
            env:
                GH_TOKEN: ${{ secrets.TOKEN }}