name: release

on:
  push:
    branches: [master]
    path:
      - "src/uel/version.py"
permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  release:
    strategy:
      matrix:
        python-version: ['3.11']
    runs-on: ubuntu-lasted
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build dependence
        run: pip install setuptools Cython
      - name: Install dependence
        run: pip install -r requirements-dev.txt
      - name: Install
        run: make install
      - name: Set github user
        run: git config user.name "user-11150"
      - name: Set github email
        run: git config user.email 3584434540@qq.com
      - name: Set github remote
        run: git remote set-url origin https://${TOKEN}@github.com/user-11150/puel
        env:
          TOKEN: ${{secrets.TOKEN}}
      - name: Release
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{secrets.PYPI_TOKEN}}
        run: python tools/release.py