name: release

on:
  push:
    tags:
    - '*'

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  release:
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build dependence
        run: pip install setuptools Cython
      - name: Install dependence
        run: pip install -r requirements-dev.txt
      - name: Build
        run: make build
      - name: Release
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{secrets.PYPI_TOKEN}}
        run: twine upload dist/**
